# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Convert Case of Repository and Organization
        id: repository_full_name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.event.repository.full_name }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          # tags: "${{ github.event.repository.full_name }}:${{ steps.meta.outputs.tags }},${{ github.event.repository.full_name }}:${{ github.sha }}" 
          tags: "${{ steps.repository_full_name.outputs.lowercase }}:${{ github.sha }}" 
          labels: ${{ steps.meta.outputs.labels }}